# Anthropic Documentation Scraper Configuration

# URLs and paths
urls:
  root: "https://docs.anthropic.com"
  base: "https://docs.anthropic.com/en/api"
  domain: "docs.anthropic.com"
  path_prefix: "/en/api/"
  sections:
    - "/en/api/getting-started"
    - "/en/api/authentication"
    - "/en/api/messages"
    - "/en/api/models"
    - "/en/api/streaming"
    - "/en/api/tools"
    - "/en/api/rate-limits"
    - "/en/api/embedding"
    - "/en/api/pricing"
    - "/en/api/client-libraries"
    - "/en/api/versioning"
    - "/en/api/content-filtering"
    - "/en/docs/quickstart"
    - "/en/api/errors"
    - "/en/api/ip-addresses"
    - "/en/api/client-sdks"
    - "/en/api/supported-regions"
    - "/en/api/getting-help"
    - "/en/api/openai-sdk"
    - "/en/api/claude-on-amazon-bedrock"
    - "/en/api/claude-on-vertex-ai"
    - "/en/api/prompt-validation"

# Excluded patterns
excluded_patterns:
  - "/feedback"
  - "/legal"
  - "/privacy"
  - "/terms"
  - "/search"
  - "?q="
  - "/api/v1/"
  - "anthropic.com/news"
  - "twitter.com"
  - "github.com"
  - "linkedin.com"
  - "facebook.com"
  - "instagram.com"
  - "youtube.com"
  - "mailto:"

# User agents for rotation
user_agents:
  - 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
  - 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15'
  - 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0'
  - 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
  - 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41'

# Output directories
directories:
  html: "anthropic_docs_html"
  markdown: "anthropic_docs_md"
  images: "anthropic_docs_images"
  full_html: "anthropic_docs_full_html"
  metadata_file: "page_metadata.json"

# Thread configuration
threading:
  worker_threads: 4
  image_threads: 8
  max_crawl_depth: 10

# Rate limiting
rate_limiting:
  max_requests_per_second: 5
  min_delay_between_requests: 0.5
  respect_robots_txt: true
  adaptive: true  # Enable adaptive rate limiting based on server responses
  max_retries: 5
  base_retry_delay: 2.0
  max_retry_delay: 20.0

# Logging
logging:
  log_file: "scraper.log"
  level: "INFO"
  
# Image processing
images:
  max_size: 800  # Maximum dimension for image optimization
  quality: 85    # JPEG quality for saved images

# Features
features:
  use_markdownify: true  # Use markdownify library instead of custom HTML->MD conversion
  cache_requests: false  # Enable HTTP request caching
  render_javascript: false  # Enable JavaScript rendering (requires additional dependencies) 